---
title: "Birth data in France"
author: "Baptiste Maingret"
date: "20/11/2019"
output: ioslides_presentation
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(plotly)
```

## Getting the data

Data downloaded from [INSEE.FR](https://www.insee.fr/fr/statistiques/series/102928992).
```{r}
RAW_PATH = "./data/raw"
PROCESSED_PATH = "./data/processed"

zip_files <- list.files(RAW_PATH, full.names = TRUE)
zip_dir <- tools::file_path_sans_ext(zip_files)
sapply(zip_dir, dir.create)
sapply(zip_files, function(x) unzip(x, exdir = tools::file_path_sans_ext(x), junkpaths = TRUE))

get_region <- function(path){
  tmp <- read.csv2(file.path(path, "caract.csv"), encoding = "UTF-8", nrows = 2, as.is = TRUE)
  tmp$Zone.géographique[[1]]
}

format_data <- function(path){
  tmp <- read.csv2(file.path(path, "valeurs_annuelles.csv"), encoding = "UTF-8", col.names = c("year", "value", "code"), skip = 3, header=FALSE)
  tmp["region"] <- get_region(path)
  tmp
}

data <- lapply(zip_dir, format_data)
data <- do.call(rbind.data.frame, data)
data
```

## Getting France geojson

```{r}
URL <- "https://raw.githubusercontent.com/gregoiredavid/france-geojson/master/regions-version-simplifiee.geojson"
geojson <- fromJSON(URL)
geojson$features$id <- geojson$features$properties$nom
write(toJSON(geojson), file.path(PROCESSED_PATH, "geojson.json")
```


## Plot 1

```{r}
p <- plot_geo() %>%
  add_trace(
    type = "choroplethmapbox",
    geojson = geojson,
    locations=data$region,
    z = data$value
  ) 
p
```

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Slide with Plot

```{r pressure}
plot(pressure)
```

