---
title: "Birth data in France"
author: "Baptiste Maingret"
date: "20/11/2019"
output: 
  ioslides_presentation: 
    smaller: yes
    widescreen: yes
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

```{r warning=FALSE, message=FALSE}
library(plotly)

RAW_PATH = "./data/raw"
PROCESSED_PATH = "./data/processed"
```


## Getting the data

Data downloaded from [INSEE.FR](https://www.insee.fr/fr/statistiques/series/102928992).
```{r warning=FALSE, message=FALSE, results='hide', echo=TRUE}
zip_files <- list.files(RAW_PATH, full.names = TRUE)
zip_dir <- tools::file_path_sans_ext(zip_files)
sapply(zip_dir, dir.create)
sapply(zip_files, function(x) unzip(x, exdir = tools::file_path_sans_ext(x), junkpaths = TRUE))

get_region <- function(path){
  tmp <- read.csv2(file.path(path, "caract.csv"), encoding = "UTF-8", nrows = 2, as.is = TRUE)
  tmp["Zone.géographique"][[1]]
}

format_data <- function(path){
  tmp <- read.csv2(file.path(path, "valeurs_annuelles.csv"), encoding = "UTF-8", col.names = c("year", "value", "code"), skip = 3, header=FALSE)
  tmp["region"] <- get_region(path)
  tmp
}

data <- lapply(zip_dir, format_data)
data <- do.call(rbind.data.frame, data)
saveRDS(data, file.path(PROCESSED_PATH, "birth_data.rds"))
# data <- readRDS(file.path(PROCESSED_PATH, "birth_data.rds"))
```

## Birth in France over 40 years

```{r}
p <- plot_ly(type = 'bar', orientation = 'v') %>%
  layout(barmode = 'stack')

for (region in unique(data$region)) {
  p <- p %>% add_trace(data=data[data$region==region,], x = ~year, y = ~value, name=region)
}

p
```
